version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout
      - run: ls -lah "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
      - run:
          command: set
          shell: cmd.exe
      - run:
          command: CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"\vcvarsall.bat x86
          shell: cmd.exe
      - run:
          command: set
          shell: cmd.exe
