version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2017
      shell: bash.exe
    steps:
      - checkout
      - run: ls -lah
      - run:
          command: set
          shell: cmd.exe
